version: '3.8'

services:
  haproxy:
    image: haproxy:2.9
    container_name: haproxy-lb
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  mongo-0:
    image: mongo:7.0.16
    container_name: mongo-0
    restart: unless-stopped
    command: mongod --port 27030 --replSet rs0
    network_mode: host
    volumes:
      - mongo-0:/data/db

  mongo-1:
    image: mongo:7.0.16
    container_name: mongo-1
    restart: unless-stopped
    command: mongod --port 27031 --replSet rs0
    network_mode: host
    volumes:
      - mongo-1:/data/db

  mongo-2:
    image: mongo:7.0.16
    container_name: mongo-2
    restart: unless-stopped
    command: mongod --port 27032 --replSet rs0
    network_mode: host
    volumes:
      - mongo-2:/data/db

volumes:
  mongo-0: {}
  mongo-1: {}
  mongo-2: {}